import 'package:flutter/material.dart';

/// Danh mục chọn cho màn tiêu chí tìm việc.
class JobCriteriaOptions {
  JobCriteriaOptions._();

  static const Color primary = Color(0xFF5E35B1);

  static const List<String> careers = [
    // Văn phòng & hành chính
    'Hành chính - Thư ký',
    'Văn phòng / Office',
    'Lễ tân / Tiếp khách',
    // CNTT & phần mềm
    'IT Phần mềm',
    'IT Phần cứng / Mạng',
    'Data / Phân tích dữ liệu',
    'AI / Machine Learning',
    'Bảo mật / An ninh mạng',
    'DevOps / Cloud',
    'QA / Tester phần mềm',
    'Game / Giải trí số',
    'Blockchain / Web3',
    'Hỗ trợ kỹ thuật (Helpdesk)',
    'Product Owner / Quản lý sản phẩm',
    // Marketing & kinh doanh
    'Marketing',
    'Digital Marketing',
    'Content Marketing / Copywriter',
    'SEO / SEM',
    'PR / Truyền thông',
    'E-commerce',
    'Bán hàng / Kinh doanh',
    'Bán hàng B2B',
    'Telesales / Tổng đài',
    'Bán lẻ / Cửa hàng',
    // Tài chính & kế toán
    'Kế toán / Kiểm toán',
    'Tài chính / Ngân hàng',
    'Bảo hiểm',
    'Chứng khoán / Đầu tư',
    'Thuế / Khai thuế',
    // Nhân sự & CSKH
    'Nhân sự',
    'Tuyển dụng / Headhunt',
    'Tư vấn / Chăm sóc khách hàng',
    // Thiết kế & sáng tạo
    'Thiết kế đồ họa',
    'UI / UX Design',
    'Kiến trúc / Quy hoạch',
    'Thiết kế nội thất',
    'Nhiếp ảnh / Video / Media',
    'Thời trang / Mỹ phẩm',
    // Kỹ thuật & sản xuất
    'Xây dựng',
    'Cơ khí / Chế tạo',
    'Điện - Điện tử',
    'Ô tô / Xe máy',
    'Sản xuất',
    'QA / QC sản xuất',
    'Kho vận / Kho bãi',
    'Mua hàng / Cung ứng',
    'Vận tải / Logistics',
    'Xuất nhập khẩu',
    // Ngành dịch vụ
    'Giáo dục / Đào tạo',
    'Gia sư / Dạy học',
    'Y tế / Dược',
    'Điều dưỡng / Hộ lý',
    'Spa / Làm đẹp',
    'Khách sạn / Nhà hàng',
    'Du lịch / Lữ hành',
    'F&B / Phục vụ ăn uống',
    // Khác ngành
    'Luật / Pháp lý',
    'Bất động sản',
    'Nông nghiệp / Thủy sản',
    'Dầu khí / Năng lượng',
    'Dệt may / Da giày',
    'In ấn / Bao bì',
    'Môi trường / HSE',
    'Hàng không / Hàng hải',
    'Viễn thông',
    'Truyền hình / Báo chí',
    'Biên - Phiên dịch',
    'Nghệ thuật / Giải trí',
    'Thể thao / Fitness',
    'Bảo vệ / An ninh',
    'Lao động phổ thông',
    'Quản lý / Điều hành',
    'Kỹ thuật viên',
    'Thực tập sinh',
    'Freelance / Làm việc từ xa',
    'Startup / Công ty khởi nghiệp',
    'Khác',
  ];

  static const List<String> locations = [
    'Hà Nội',
    'TP.HCM',
    'Đà Nẵng',
    'Hải Phòng',
    'Cần Thơ',
    'An Giang',
    'Bà Rịa - Vũng Tàu',
    'Bắc Giang',
    'Bắc Ninh',
    'Bình Dương',
    'Bình Định',
    'Bình Phước',
    'Bình Thuận',
    'Cà Mau',
    'Đắk Lắk',
    'Đồng Nai',
    'Đồng Tháp',
    'Hà Tĩnh',
    'Hưng Yên',
    'Khánh Hòa',
    'Kiên Giang',
    'Lâm Đồng',
    'Long An',
    'Nghệ An',
    'Ninh Bình',
    'Phú Thọ',
    'Quảng Nam',
    'Quảng Ngãi',
    'Quảng Ninh',
    'Tây Ninh',
    'Thái Nguyên',
    'Thanh Hóa',
    'Vĩnh Long',
  ];
}
