// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEI7fY6d3SKawd7CmF4_JAUW5nKp9yjKU',
    appId: '1:630246371829:web:241e8c34fb722c600630bc',
    messagingSenderId: '630246371829',
    projectId: 'timkiemvieclam-711c6',
    authDomain: 'timkiemvieclam-711c6.firebaseapp.com',
    storageBucket: 'timkiemvieclam-711c6.firebasestorage.app',
    measurementId: 'G-7N0DSRKGN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUZMzGdvoSITFw0ObZrP9RPR0GBNuAhR8',
    appId: '1:630246371829:android:1e6ef76a2d01b59a0630bc',
    messagingSenderId: '630246371829',
    projectId: 'timkiemvieclam-711c6',
    storageBucket: 'timkiemvieclam-711c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE3TbAVIb6RF3G3XQnkGFnBaAok8CTO14',
    appId: '1:630246371829:ios:b439e61ffd050dcb0630bc',
    messagingSenderId: '630246371829',
    projectId: 'timkiemvieclam-711c6',
    storageBucket: 'timkiemvieclam-711c6.firebasestorage.app',
    iosBundleId: 'com.example.viecnow',
  );
}
